// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeSchedule.Models;

namespace WeSchedule.Migrations
{
    [DbContext(typeof(ScheduleSetup))]
    partial class ScheduleSetupModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeSchedule.Models.Availability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DayId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<int>("empID")
                        .HasColumnType("int");

                    b.Property<int?>("epmstpid")
                        .HasColumnType("int");

                    b.Property<DateTime>("et")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("st")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("epmstpid");

                    b.ToTable("availability");
                });

            modelBuilder.Entity("WeSchedule.Models.EmployeeSetup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wage")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("employeeSetup");
                });

            modelBuilder.Entity("WeSchedule.Models.Availability", b =>
                {
                    b.HasOne("WeSchedule.Models.EmployeeSetup", "epmstp")
                        .WithMany()
                        .HasForeignKey("epmstpid");

                    b.Navigation("epmstp");
                });
#pragma warning restore 612, 618
        }
    }
}
